version: '3.8'

services:
  cms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - cms-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: cms-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cms
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: cmspassword
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cms-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cms-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge

volumes:
  dbdata:
